### ISSUE TITLE
pip install of logstash-python-formatter corrupts python-logstash

### ISSUE THREAD

**Issue by krishnadubba** [mbarrientos/logstash-python-formatter#2]
Hi,
Not sure if this intended but "pip install logstash-python-formatter" corrupts previous installation of python-logstash (a different package). If you look at the folders in :
https://pypi.org/project/logstash-python-formatter/#files

there are two folders "logstash" and "logstash_formatter" with same contents. Not sure why the additional folder "logstash" is there. This folder when installed corrupts the python-logstash package.

Cheers,
dksr

**Comment by mbarrientos** [comment]
Hi @krishnadubba 
thanks for reporting this, it looks like that folder was from a previous version of the package. 

It should be fixed on v0.1.2.
